// Régénère les deux tableaux dérivés du plan de quais.
//
//   docs/YAMANOTE_PLATFORM_MATRIX.md  - ce que le runtime rend, quai par quai
//   docs/PLATFORM_EVIDENCE.md         - d'où vient chaque valeur, et à quel titre
//
// Ni l'un ni l'autre n'est une seconde source : les deux se lisent entièrement
// dans `stationPlatformSetFor`. Ils étaient tenus à la main, donc en retard
// d'une correction sur les données - le relevé de janvier 2026 en a décalé
// quinze lignes d'un coup.
//
//   node scripts/platform-docs.mjs           écrit les deux fichiers
//   node scripts/platform-docs.mjs --check   sort en erreur s'ils ont dérivé

import { readFileSync, writeFileSync } from 'node:fs';
import { register } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

register('../tests/fixtures/ts-resolve.mjs', import.meta.url);

const { STATIONS } = await import('../src/data/stations.ts');
const { stationPlatformSetFor } = await import('../src/data/platforms.ts');

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECKED = '2026-01-31';

/** Toutes les voies de la boucle, régulières puis terminales, dans l'ordre JY. */
function rows() {
  const out = [];
  for (const station of STATIONS) {
    const set = stationPlatformSetFor(station.jy);
    for (const direction of ['inner', 'outer']) {
      const side = set[direction];
      for (const profile of [side.primary, ...side.alternatives]) {
        out.push({ label: `${station.jy} ${station.romaji}`, profile });
      }
    }
  }
  // L'ordre historique des deux tableaux : les deux sens d'une gare se suivent,
  // et la voie alternative suit la voie régulière de son sens.
  return out;
}

function psdCell(profile) {
  const fallback = profile.evidence?.platformDoors?.confidence === 'estimated' ? 'fallback ' : '';
  return `${fallback}${profile.platformDoors.installed ? 'yes' : 'no'}`;
}

function matrix(all) {
  const head = [
    '# Yamanote platform matrix',
    '',
    'Generated from `YAMANOTE_PLATFORMS` through `stationPlatformSetFor` by'
      + ' `scripts/platform-docs.mjs`; it is not a second runtime matrix.'
      + ` Checked ${CHECKED}.`,
    '',
    '| Station | Direction | Platform | Next | Role | Doors | PSD |',
    '|---|---|---:|---|---|---|---|',
  ];
  const body = all.map(({ label, profile: p }) =>
    `| ${label} | ${p.direction} | ${p.platform} | ${p.nextStationCode} |`
    + ` ${p.serviceRoles.join(', ')} | ${p.doorSide} | ${psdCell(p)} |`);
  return `${[...head, ...body].join('\n')}\n`;
}

function evidence(all) {
  const head = [
    '# Platform evidence',
    '',
    'Each runtime value is recorded with its provenance. Door sides come from the'
      + ' January 2026 JR East survey, cross-checked against the track plans;'
      + ' platform-door states are still a conservative fallback from'
      + ` \`stationLayouts.psd\`. Generated by \`scripts/platform-docs.mjs\`. Checked ${CHECKED}.`,
    '',
    '| Station | Direction | Platform | Next | Door side | PSD | Chime | Voice | Confidence | Source note |',
    '|---|---|---:|---|---|---|---|---|---|---|',
  ];
  const body = all.map(({ label, profile: p }) => {
    const chime = p.approachChime?.profileId ?? 'generic fictive fallback';
    const voice = p.automaticVoice?.japaneseRole ?? '-';
    const doorEvidence = p.evidence?.doorSide;
    const note = doorEvidence?.sourceNote ?? '-';
    return `| ${label} | ${p.direction} | ${p.platform} | ${p.nextStationCode} |`
      + ` ${p.doorSide} | ${psdCell(p)} | ${chime} | ${voice} |`
      + ` ${doorEvidence?.confidence ?? '-'} | ${note} |`;
  });
  return `${[...head, ...body].join('\n')}\n`;
}

const all = rows();
const files = [
  ['docs/YAMANOTE_PLATFORM_MATRIX.md', matrix(all)],
  ['docs/PLATFORM_EVIDENCE.md', evidence(all)],
];

if (process.argv.includes('--check')) {
  let stale = false;
  for (const [path, content] of files) {
    if (readFileSync(join(ROOT, path), 'utf8') !== content) {
      console.error(`${path} a dérivé des données : node scripts/platform-docs.mjs`);
      stale = true;
    }
  }
  process.exit(stale ? 1 : 0);
}

for (const [path, content] of files) {
  writeFileSync(join(ROOT, path), content);
  console.log(`écrit ${path} (${all.length} voies)`);
}
